language: node_js

node_js:
  - "10.17.0"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm explore npm -g -- npm install node-gyp@latest
  - rm package-lock.json

install: npm install

before_script:
  - npm install -g gulp-cli

script: gulp tslint

notifications:
  email: false